### ISSUE TITLE
Can't decode video

### ISSUE THREAD

**Issue by baardev** [Spidy-PS/Steganography-Tools#6]
```
1. Encode the Text message
2. Decode the Text message
3. Exit
Enter the Choice:2
Traceback (most recent call last):
  File "/home/jw/store/src/Steganography-Tools/./Steganography.py", line 631, in <module>
    main()
  File "/home/jw/store/src/Steganography-Tools/./Steganography.py", line 619, in main
    vid_steg()
  File "/home/jw/store/src/Steganography-Tools/./Steganography.py", line 591, in vid_steg
    decode_vid_data(a)
UnboundLocalError: local variable 'a' referenced before assignment

```

**Comment by longstegano** [comment]
when you encode video, you return _frame, when you decode video, you just use this _frame, you did not use the video. It's meaningless!!!

**Comment by Priyansh-15** [comment]
Hi @baardev , Did you fork the repo correctly, The decode for text messege is working fine, can you please re-verify the issue and if it still persist please let me know with details. 
Thanks !! 
@Priyansh-15
